### ISSUE TITLE
Crash when putting a flipbook nested in a button

### ISSUE THREAD

**Issue by joshmmo** [dorgonman/HorizonUIPluginDemo#1]
Every time I try and put a UMG Horizon Flipbook nested inside a button the editor crashes. Happens every time.

My main goal here is I need to do stuff when the flipbook is touched.

Thanks

**Comment by dorgonman** [comment]
hi, thank you for your bug report, I will take a look and fix it ASAP.

**Comment by dorgonman** [comment]
hi, here is hotfix for this bug:

void UHorizonFlipbookWidget::OnWidgetRebuilt() {
	Super::OnWidgetRebuilt();


	AnimationDeltaTime = 0;
	bool result = RemoveChild(ImageWeakPtr.Get());
	if (PaperFlipbook) {
		FName name = *FString::Printf(TEXT("%s.image"), *FString(GetName()));
		ImageWeakPtr = NewObject<UImage>(this->Slot, name);
		AddChild(ImageWeakPtr.Get());
		ImageWeakPtr->SetVisibility(ESlateVisibility::HitTestInvisible);


		//loop throught parent
		UWidget* pTargetWidget = this;
		UCanvasPanelSlot* pCanvasPanelSlot = nullptr;// Cast<UCanvasPanelSlot>(Slot);

		do {

			pCanvasPanelSlot = Cast<UCanvasPanelSlot>(pTargetWidget->Slot);
			if (pCanvasPanelSlot) {
				break;
			}
			else {
				if (pTargetWidget) {
					pTargetWidget = pTargetWidget->GetParent();
					verifyf(pTargetWidget, TEXT("oops! something error"));
				}
				else {
					break;
				}
			}

		} while (pCanvasPanelSlot == nullptr);

		verifyf(pCanvasPanelSlot, TEXT("oops! something error"));
		UCanvasPanelSlot* imageCanvasPanelSlot = Cast<UCanvasPanelSlot>(ImageWeakPtr->Slot);
		if (imageCanvasPanelSlot) {
				imageCanvasPanelSlot->SetSize(pCanvasPanelSlot->GetSize());
		}

		ImageWeakPtr->SetColorAndOpacity(ColorAndOpacity.GetSpecifiedColor());
	}

}

I am still working on a general solution.
