### ISSUE TITLE
Size to content with Dialogue text

### ISSUE THREAD

**Issue by Avatarus-one** [dorgonman/HorizonUIPluginDemo#10]
Enabling **Size To Content** setting along with **Is Dialogue Msg Text** breaks the text output.
When a text block is not anchored to the sides, text doesn't appear at all. If you anchor the block, it will only output 1 line of the text per page. 

![image](https://user-images.githubusercontent.com/4481128/177427563-247c8f42-e261-43e6-98df-6fa0d7024696.png)

A setting that forces a singular page would be very useful in this scenario.

**Comment by dorgonman** [comment]
hi, thanks your feedback.

Currently, DialogueMsgTextBlock didn't support SizeToContent use case, as workaround, you can put the widget under SizeBox and override Widget and Height manually

![image](https://user-images.githubusercontent.com/1768035/177459646-da012ad3-4356-4fed-abf0-dfa2547a619b.png)

or you can try to add follow code to HorizonDialogueMsgTextBlock.cpp and recompile it:

`
void UHorizonDialogueMsgTextBlock::RebuildPageInfoList()
{
...
	// setup line init info 
	auto& geometry = GetCachedGeometry();
	float canvasHeight = geometry.Size.Y;
//  =================Support Size to Content==============
	auto pCanvasPanelSlot = UHorizonWidgetFunctionLibrary::GetParentCanvasPanelSlot(this);
	if(pCanvasPanelSlot)
	{
		if(pCanvasPanelSlot->bAutoSize)
		{
			float maxLineHeight = (float)Font.Size;
			for(auto& it : DialogueLineInfoList)
			{
				maxLineHeight = FMath::Max(maxLineHeight, 
							it.MaxLineHeight + FMath::Max(LineMargin.Top, LineMargin.Bottom));
			}
			canvasHeight = maxLineHeight * (DialogueLineInfoList.Num() + 1);
		}
	}
//  =================Support Size to Content==============
	...
}
`

Thanks

**Comment by Avatarus-one** [comment]
Your fix works perfectly for my case.
However, I've noticed a similar issue with panels that support alignment.

![image](https://user-images.githubusercontent.com/4481128/177481490-3c1f73aa-a11a-4130-9367-f5cb4358e6a9.png)

If you add a dialogue block with settings like these, it will also output only one line of text.

**Comment by dorgonman** [comment]
hi, thanks for your feedbacks.

I know the issue, but since my other projects didn't layout our dialogue like this,  so I didn't trying to fix it.
Do you have any use case that you need to align your Dialogue like this? and the what is expected output you want to see?

**Comment by Avatarus-one** [comment]
I used vertical box as a workaround to make the text centered vertically. But since SizeToContent is fixed now, I probably won't need other containers than canvas.

![image](https://user-images.githubusercontent.com/4481128/177628175-ed050d23-a981-4361-b33b-c09ff12b797c.png)

**Comment by dorgonman** [comment]
In next release version, maybe 5.1.0, I will try to implement VerticalPanel support using similar implementation for CanvasPanel, although it won't get AutoPaged, but at least it works for someone who want to layout Dialogue with VerticalPanel.

**Comment by dorgonman** [comment]
About size to content, just found out it won't work at runtime, as workaround, you need to enable ForceRebuildDialogueMsgText

![image](https://user-images.githubusercontent.com/1768035/177673882-f78e60f7-d4d8-47e4-a38f-7e6d73fad367.png)

**Comment by Avatarus-one** [comment]
Looks like the issue with Size To Content is still there. When a dialogue block contains only text with or without `<text>` tags, the last line will be moved to the next page. Adding images or `<br/>` at the end fixes it.

**Comment by dorgonman** [comment]
Just try it without <text> tag for size to content, it works fine at my end, how did you layout your widget?

![image](https://user-images.githubusercontent.com/1768035/177899592-4fd523ef-4bff-4877-8402-98289042d23a.png)

**Comment by Avatarus-one** [comment]
I found out that the bug only happens when I have Line Margin Top and Bottom set to 0.

![image](https://user-images.githubusercontent.com/4481128/177928432-cb772e82-b15a-444e-8e18-95af91933534.png)

**Comment by dorgonman** [comment]
Oh, then +1 to line number can fix that:
canvasHeight = maxLineHeight * (DialogueLineInfoList.Num() + 1);

**Comment by Avatarus-one** [comment]
I've changed you code a bit. This fixed the issue for me.
```
	bool bForceSinglePage;
	auto pCanvasPanelSlot = UHorizonWidgetFunctionLibrary::GetParentCanvasPanelSlot(this);
	if (pCanvasPanelSlot)
	{
		if (pCanvasPanelSlot->bAutoSize)
			bForceSinglePage = true;
	}	
```
```
		if ((currentPageHeight >= maxPageHeight && !bForceSinglePage) ||
			(lineInfo.bNewPage && !FMath::IsNearlyZero(currentPageHeight)) // Handle NewPage tag
```

**Comment by dorgonman** [comment]
It is good idea, but I will rename bForceSinglePage to bIgnoreMaxPageHeight

Here will be my Implementation for next version:
```

void UHorizonDialogueMsgTextBlock::Tick(float DeltaTime) {

...
	if (bNeedRebuildDialogueMsgText)
	{
//===============Modify===============
		bool bAutoSize = false;
		auto pCanvasPanelSlot = Cast<UCanvasPanelSlot>(Slot);
		if(pCanvasPanelSlot)
		{
			bAutoSize = pCanvasPanelSlot->bAutoSize;
		}
		auto geometry = GetCachedGeometry();
		if (geometry.Size.X > 0 || bForceRebuildDialogueMsgText || bAutoSize)
		{
//===============Modify===============
			bNeedRebuildDialogueMsgText = false;
			RebuildDialogueMsgTextBlock();
			OnRebuildDialogueDelegate.Broadcast();
			OnRebuildDialogueDelegateNative.Broadcast();
		}
		return;
	}
...
}
void UHorizonDialogueMsgTextBlock::RebuildPageInfoList()
{
	DECLARE_HORIZONUI_QUICK_SCOPE_CYCLE_COUNTER(UHorizonDialogueMsgTextBlock, RebuildPageInfoList)
	DialoguePageInfoList.Empty();

	// setup line init info 
	auto& geometry = GetCachedGeometry();
	float canvasHeight = geometry.Size.Y;

//===============Modify===============
	bool bIgnoreMaxPageHeight = false;
	auto pCanvasPanelSlot = Cast<UCanvasPanelSlot>(Slot);
	if(pCanvasPanelSlot)
	{
		if(pCanvasPanelSlot->bAutoSize)
		{
			bIgnoreMaxPageHeight = true;
		}
	}
	auto pVerticalSlot = Cast<UVerticalBoxSlot>(Slot);
	if (pVerticalSlot)
	{
		switch(pVerticalSlot->VerticalAlignment)
		{
			case VAlign_Fill:
			{
				// use geometry.Size.Y
			}
			break;
			default:
			{
				bIgnoreMaxPageHeight = true;
			}
			break;
		}

	}
	auto pScaleBoxSlot = Cast<UScaleBoxSlot>(Slot);
	if (pScaleBoxSlot)
	{
		bIgnoreMaxPageHeight = true;
	}
//===============Modify===============
	int32 startLineIndex = 0;
	int32 currentLineIndex = 0;
	float currentPageHeight = 0;
	while (currentLineIndex < DialogueLineInfoList.Num())
	{
		const auto& lineInfo = DialogueLineInfoList[currentLineIndex];
		float maxPageHeight = FMath::Max((float)Font.Size, canvasHeight - lineInfo.MaxLineHeight);
//===============Modify===============
		if ((currentPageHeight >= maxPageHeight && !bIgnoreMaxPageHeight) ||
			(lineInfo.bNewPage && !FMath::IsNearlyZero(currentPageHeight)) // Handle NewPage tag
		   )
		{
//===============Modify===============
			if (startLineIndex == currentLineIndex)
			{
				++currentLineIndex;
				ensureMsgf(false, TEXT("oops! something error"));
			}

			DialoguePageInfoList.Emplace(FHorizonDialoguePageInfo(startLineIndex, currentLineIndex, currentPageHeight));
			startLineIndex = currentLineIndex;
			currentPageHeight = 0;
		}
		else
		{
			if (FMath::IsNearlyZero(currentPageHeight))
			{
				currentPageHeight += LineMargin.Top;
			}
			else
			{
				currentPageHeight += LineMargin.Bottom;
			}

			currentPageHeight = currentPageHeight + lineInfo.MaxLineHeight;
			++currentLineIndex;

		}

	}
	//last page
	DialoguePageInfoList.Emplace(FHorizonDialoguePageInfo(startLineIndex, currentLineIndex, currentPageHeight));

}
void UHorizonDialogueMsgTextBlock::RebuildLineInfoList()
{
...
		if (nullptr == pTextBlockCanvasPanelSlot)
		{
			widgetWidth = geometry.Size.X;
//===============Modify===============
			// Hotfix ScaleBox use case
			// TODO: Refactor to more general solution
			UScaleBoxSlot* pScaleBoxSlot = Cast<UScaleBoxSlot>(Slot);
			if (pScaleBoxSlot)
			{
				widgetWidth = Text.ToString().Len() * Font.Size;
			}
//===============Modify===============
		}
		else
		{
			widgetWidth = FMath::Max(pTextBlockCanvasPanelSlot->GetSize().X, geometry.Size.X);
		}
...
}


```

**Comment by Avatarus-one** [comment]
Thanks, I'll be looking for the update. 👍

**Comment by dorgonman** [comment]
Just test page feature, it works as my expected, It will force contents under page tag to seperate pages. What specific issue did you see?

https://gyazo.com/3a86320240ef9741a511ec4d5677eba9

**Comment by Avatarus-one** [comment]
Considering, that Size to Content is enabled, the expected output would be this:

![image](https://user-images.githubusercontent.com/4481128/178909002-e5513887-cef0-4341-a8bd-7ef99076473e.png)

**Comment by dorgonman** [comment]
This issue is very tricky, since unreal's cached geometry are doing something, currently I don't have idea how to fix that.

Did you find out this issue will affect your runtime layout? if not, I will not trying to fix that, because it looks like not affect runtime behavior.

**Comment by Avatarus-one** [comment]
This is how it looks in runtime with an actual text.
![image](https://user-images.githubusercontent.com/4481128/178913067-af953f46-ff51-40d1-901c-cdfe3d074f73.png)

If it's had to fix, I'll revert texts back to using arrays, it's not a big deal.
