### ISSUE TITLE
SetTextAndRebuildDialogue is not work

### ISSUE THREAD

**Issue by mirchd** [dorgonman/HorizonUIPluginDemo#4]
the UHorizonDialogueMsgTextBlock can set text in blueprint, but if I set text in c++ code by call **SetTextAndRebuildDialogue**, it does not work.
the text is the same

**Comment by dorgonman** [comment]
hi, It should work, could your please give me your test example?

**Comment by dorgonman** [comment]
hi, 
I could not reproduce your issues, 
could you please provide the steps or an example project?

**Comment by mirchd** [comment]
visual studio alert in this:
[https://ibb.co/mAcEfo](url)
call stack:
[https://ibb.co/etf6t8](url)

the param of my Horizon Dialogue Msg Text Block:
[https://ibb.co/j3KS0o](url)

when I call "**SetTextAndRebuildDialogue**" , with FText 
"<text color="#FFFFFFFF">指挥官，您确定使用以下超级大仙丹将</text><text color="#FFFF00FF">莫扎特</text><text color="#FFFFFFFF">升级到</text><text color="#FFFF00FF">40级</text><text color="#FFFFFFFF">吗？</text>"

the bug will be reproduced,
please hlp,~

**Comment by dorgonman** [comment]
hi,
just try to reproduce your case, but I still can't reproduce, here is [the video](https://1drv.ms/v/s!AvccKTmLQK0JgYttkNBHamBU-WnKCw)

**Comment by mirchd** [comment]
thanks for replying so quickly~
when I input these texts to blueprint setting window, Content->Text，and then click "compile" btn, vs assertion .
my plugin version is 4.18.1

may be these bug is related to the engine build option or other reason
but it does not effect the apk whiich I package.

and I don't konw why these can't be reproduce in blueprint function calling.

**Comment by dorgonman** [comment]
The only possible is that your text contain some non UTF8 character, please ensure text you input are converted into UTF8 encoding.

**Comment by mirchd** [comment]
my text is not UTF8 encoding, this is the reason cause these bug~
thank you very much
