### ISSUE TITLE
How would I nest Text

### ISSUE THREAD

**Issue by Taikatou** [dorgonman/HorizonUIPluginDemo#5]
I want one word to be different colour of the rest here is my rtf

`<text color="#0000FFFF">
    Step 1: Keep your cursor on the moving
</text>
<text color="#FF0000AA">
    Yellow
</text>
<text color="#0000FFFF">
    ball or running man as long as possible
</text>`

I have tried adding spaces between the word yellow to space it out to no avail, any help?

Thank you :D

**Comment by dorgonman** [comment]
hi, you should add ```&nbsp;``` before and after your text inorder to add space in text block:
![image](https://user-images.githubusercontent.com/1768035/40154424-d9d78ff6-59c0-11e8-9fed-efbb3717a27c.png)
