### ISSUE TITLE
Text wrapping sometimes doesn't remove space at the beginning of the new line

### ISSUE THREAD

**Issue by Bluepuff71** [dorgonman/HorizonUIPluginDemo#6]
Sometimes when text is wrapped, a space is added to the beginning of the new line.

The original text in the image is "This dialog box is having an issue". You can see that the space between "an" and "issue" is not removed.

![image](https://user-images.githubusercontent.com/11048124/93690619-10b17c80-faa0-11ea-9fc8-aee416009745.png)

**Comment by dorgonman** [comment]
Thanks your feedback, I will add it to my backlog.

**Comment by dorgonman** [comment]
Fixed in 4.26.0 released.
