### ISSUE TITLE
HorizonDialogueMsgSpaceDecorator

### ISSUE THREAD

**Issue by Avatarus-one** [dorgonman/HorizonUIPluginDemo#9]
Readme file mentions HorizonDialogueMsgSpaceDecorator, but it's not included in the plugin.
![image](https://user-images.githubusercontent.com/4481128/177219106-9b3b40d3-8229-4711-b012-70e0c06be293.png)

Without it, segments are rendered without spaces.
```
<text>You got the </text><text style="Red">Master Sword</text><text>!</text>
```
![image](https://user-images.githubusercontent.com/4481128/177219404-de552c24-054f-498c-a19c-5c09802407d1.png)

Adding `&nbsp;` is one way to fix it, but, it's effect is not always desired.

**Comment by dorgonman** [comment]
hi, 
Space Decorator are implemented in 5.0.1, please make sure your plugin are updated to latest version.

![image](https://user-images.githubusercontent.com/1768035/177234843-660d6b72-1fa8-4650-b855-803d351190bd.png)

**Comment by Avatarus-one** [comment]
We're using Unreal 4.27. Is the latest version compatible with it?

вт, 5 июл. 2022 г., 04:01 dorgon chang ***@***.***>:

**Comment by Avatarus-one** [comment]
Here's the latest one available from the marketplace.
![image](https://user-images.githubusercontent.com/4481128/177261445-a3e8d460-ffb1-405d-be21-954d40e2906a.png)

**Comment by dorgonman** [comment]
hi, you can get latest version, remove "EngineVersion" line from .plugin and recompile it for 4.27, it should works,

**Comment by Avatarus-one** [comment]
The version for UE5 works fine, thank you.
